### ISSUE TITLE
Two-space indentation

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1847] opened 2023-06-15 13:43 UTC
This is a bike-shedding issue that we should should either act on now, while we are in the middle of reformatting pain, or close permanently. I'm fine either way.

The issue is that two-space indentation does not look very good with a two-character delimiters for target code. For example, from our test suite:
```
  reaction(startup, a) -> a {=
    if (!a->is_present) {
        if (self->offset == 0) {
            printf("Hello World!\n");
            self->success = true;
        } else {
            lf_schedule(a, self->offset);
        }
    } else {
        printf("Hello World 2!\n");
        self->success = true;
    }
  =}
```
The last two lines are what I'm concerned about. This does not look good to me.  A separate issue is that the code body indentation is left alone (as it probably should be), and in this case, it uses four spaces.  With four-space indentation all around, it looks like this:
```
  reaction(startup, a) -> a {=
      if (!a->is_present) {
          if (self->offset == 0) {
              printf("Hello World!\n");
              self->success = true;
          } else {
              lf_schedule(a, self->offset);
          }
      } else {
          printf("Hello World 2!\n");
          self->success = true;
      }
  =}
``` 
This looks better to me.  I do not feel strongly about this and am fine with closing this issue if we want to stick to two-space indentation.

**Comment by cmnrd** [comment] 2023-06-15 15:53
Just for completeness, I would like to add the example with 2 space indentation also in the target code.

```
  reaction(startup, a) -> a {=
    if (!a->is_present) {
      if (self->offset == 0) {
        printf("Hello World!\n");
        self->success = true;
      } else {
        lf_schedule(a, self->offset);
      }
    } else {
      printf("Hello World 2!\n");
      self->success = true;
    }
  =}
```

I can relate to the concern about the last two lines. To me personally, however, it still looks fine with the 2 spaces. Maybe this is because I am used to 2 space indentation from other projects. So my vote would be for closing this issue.

I am undecided about what we should do about the target code. We could try to hook in with the target language formatters, but I am very skeptical about this path. The root of the problem is that we are mixing two languages, and perhaps we shouldn't do this in the first place.

**Comment by lhstrh** [comment] 2023-06-17 05:22
I'm not sure that changing from 2 to 4 spaces fixes anything. 

If you are expecting the closing brace to be one indentation unit of indentation removed from the inner the code block, then that also won't be the case with 4-space indentation: the `}` will be 3, not 4 spaces removed from the inner `}` (due to the preceding `=`).

I agree that it may be easier to spot the difference between 1 and 2 spaces than between 3 and 4, but that doesn't change the fact that the indentation will always be off by one because of the extra character that we use...

**Comment by edwardalee** [comment] 2023-06-17 16:47
OK, I give up.  Please adjust all the tests and examples so that they use two-space indents in the reaction bodies.  Currently, with the mix, they look pretty ugly.

**Comment by edwardalee** [comment] 2023-06-21 13:10
One request is still not done: setup instructions for IntelliJ and VS Code need to explain how to set default spacing to two, which no IDE that I've encountered defaults to.

**Comment by cmnrd** [comment] 2023-06-21 13:28
This was autoclosed by the merge.

**Comment by lhstrh** [comment] 2023-06-21 17:14
In VSCode, the default setting is `Detect Indentation`, which I have found to work fine. Perhaps @a-sr knows how to instruct Epoch to use two-space indentation.

**Closed** 2023-07-06 10:04 UTC
Labels: formatter

**Comment by a-sr** [comment] 2023-07-06 14:53
> Perhaps @a-sr knows how to instruct Epoch to use two-space indentation.

https://github.com/lf-lang/epoch/pull/21 will configure Epoch to use 2 spaces for tabs.
