### ISSUE TITLE
The C tracing deadlocks for larger programs

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#634] opened 2021-10-19 14:17 UTC
See discussion in #481.

**Comment by Soroosh129** [comment] 2021-10-19 14:52
Just as a note, I fixed one or two bugs in the C target's tracing framework in #532. I don't think this deadlock is caused by those fixes since the issue seems to be older than the fixes by a wide margin. 

The benchmarks branch is now even with master thanks to @cmnrd, so a git pull will bring in my fixes.

**Comment by edwardalee** [comment] 2021-10-20 22:05
This is now fixed. The problem was that with tracing turned on, there is an upper bound on the number of distinct kinds of tracing events you can have.  This bound was being exceeded, and the code was neither issuing a warning nor releasing a mutex lock, hence causing a deadlock.  Now it does both.  Everyone will have to do the `git submodule update --init --recursive` song and dance.

**Closed as completed by edwardalee** 2021-10-20 22:05 UTC
Labels: bug, c
