### ISSUE TITLE
Extra folders generated for main reactors in imported files in the Python target

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#768] opened 2021-11-22 20:46 UTC
suppose we have two programs:

`HelloWorld.lf`
```
target Python;

reactor HelloWorld2 {
    reaction(startup) {=
        # do nothing
    =}
}

main reactor {
    a = new HelloWorld2();
}
```

`b.lf`
```
target Python;

import HelloWorld2 from "HelloWorld.lf";

main reactor {
    a = new HelloWorld2();
}
```

When I compile `b.lf` with lfc, a folder for the main reactor in the imported file also gets generated, which it shouldn't.

**Comment by lhstrh** [comment] 2021-12-01 16:00
@cmnrd: Why is this marked as `invalid`?

**Comment by cmnrd** [comment] 2021-12-08 15:45
Because it seemed to me that "This doesn't seem right" fits this issue. I don't think this issue qualifies as a bug. But of course someone who knows the Python target and its expected behavior better than me can update the labels.

**Comment by oowekyala** [comment] 2021-12-08 23:42
Maybe this "invalid" label should be renamed to "wrong-codegen" or something. To me an "invalid" label means that the issue itself is invalid, eg because the behavior is actually valid although the author didn't expect it, or the issue is a duplicate or so

**Comment by lhstrh** [comment] 2021-12-08 23:48
@oowekyala: I thought the same; I thought the issue was meant to be labeled as "invalid." I would guess that this is just a `bug`, no?

**Closed** 2022-02-10 03:08 UTC
Labels: invalid, T-Python
