### ISSUE TITLE
preamble is always in included

### ISSUE THREAD

**Issue by tanneberger** [lf-lang/lingua-franca#2156] opened 2024-01-19 14:38 UTC
## Problem Statement 

```
target Cpp; 

import Test1 from "./test1.lf"
// preamble in file `test1.lf` is still included even if the importet Reactor is never used 

main reactor {
    x  = new Test1(); 
    // only when using the importet reactor the code is generated and the program compiles
    // if the reactor is not used no code is generated and the include fails. 
}
```

-> Resulting Error is that it cannot find the preamble of test1 because no code was generated for that reactor.

## Proposed Fix
- only generate the include statement of the preamble if one of the imported reactors are actually used.

**Comment by cmnrd** [comment] 2024-01-22 18:29
This is a duplicate of https://github.com/lf-lang/lingua-franca/issues/487. I don't know what the correct behavior should be. Should the preamble be included (correctly) anyway, or not included at all if the reactor is not used?

**Closed** 2024-01-26 02:55 UTC
Labels: bug, cpp
