### ISSUE TITLE
Recompile fails without deleting `src-gen` folder manually

### ISSUE THREAD

**Issue by byeong-gil** [lf-lang/lingua-franca#1592] opened 2023-02-16 02:20 UTC
When I recompile the program without deleting `src-gen` folder manually, it fails.
For example, if I compile `Hello.lf` in `lingua-franca/test/C/src/` and put some changes and recompile it, it fails. 
After I delete the `src-gen` folder, it can be compiled.

I think the code generator does not clean the existing generated code automatically.

**Comment by cmnrd** [comment] 2023-02-17 14:52
Are you using a release artifact or your own build from our master branch? There is a known issue (https://github.com/lf-lang/lingua-franca/issues/1460), but it should be fixed on master.

**Comment by byeong-gil** [comment] 2023-02-17 23:09
I use ```./gradlew runLfc --args test/C/src/Hello.lf``` command to compile. 
This is the procedure that makes an error in my local computer (ubuntu 20.04).

1. `git pull` and `git submodule update`
2. run `./gradlew runLfc --args test/C/src/Hello.lf`
3. Make any changes in `test/C/src/Hello.lf`. In my case, I put simple print code, `printf("Hello");` into it.
4. run `./gradlew runLfc --args test/C/src/Hello.lf` again and it produces these error.
```
[ 19%] Building C object core/CMakeFiles/core.dir/lf_token.c.o
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c: In function ‘_lf_physical_time’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:201:38: error: expected ‘)’ before ‘PRINTF_TIME’
[ 19%] Building C object core/CMakeFiles/core.dir/tag.c.o
  201 |     LF_PRINT_DEBUG("Physical time: " PRINTF_TIME
[ 23%] Building C object core/CMakeFiles/core.dir/threaded/reactor_threaded.c.o
      |                                      ^~~~~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/../include/core/utils/util.h:210:36: note: in definition of macro ‘LF_PRINT_DEBUG’
  210 |                     lf_print_debug(format, ##__VA_ARGS__); \
      |                                    ^~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c: At top level:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:229:20: error: unknown type name ‘_lf_time_type’; did you mean ‘__time_t’?
  229 | instant_t _lf_time(_lf_time_type type) {
      |                    ^~~~~~~~~~~~~
      |                    __time_t
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c: In function ‘lf_time_logical’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:251:12: warning: implicit declaration of function ‘_lf_time’ [-Wimplicit-function-declaration]
  251 |     return _lf_time(LF_LOGICAL);
      |            ^~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:251:21: error: ‘LF_LOGICAL’ undeclared (first use in this function)
  251 |     return _lf_time(LF_LOGICAL);
      |                     ^~~~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:251:21: note: each undeclared identifier is reported only once for each function it appears in
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c: In function ‘lf_time_logical_elapsed’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:258:21: error: ‘LF_ELAPSED_LOGICAL’ undeclared (first use in this function)
  258 |     return _lf_time(LF_ELAPSED_LOGICAL);
      |                     ^~~~~~~~~~~~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c: In function ‘lf_time_physical’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/tag.c:267:21: error: ‘LF_PHYSICAL’ undeclared (first use in this function)
  267 |     return _lf_time(LF_PHYSICAL);
      |                     ^~~~~~~~~~~
.
.
.
      |                  ^~~~~~~~~~~~~~~~
In file included from /home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:49:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor.h:790:18: note: previous declaration of ‘_lf_schedule_int’ was here
  790 | trigger_handle_t _lf_schedule_int(void* action, interval_t extra_delay, int value);
      |                  ^~~~~~~~~~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c: In function ‘_lf_check_deadline’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:1309:28: warning: initialization of ‘reaction_t *’ {aka ‘struct reaction_t *’} from incompatible pointer type ‘struct reaction_t *’ [-Wincompatible-pointer-types]
 1309 |     reaction_t* reaction = self->executing_reaction;
      |                            ^~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c: In function ‘_lf_invoke_reaction’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:1327:57: warning: assignment to ‘struct reaction_t *’ from incompatible pointer type ‘reaction_t *’ {aka ‘struct reaction_t *’} [-Wincompatible-pointer-types]
 1327 |     ((self_base_t*) reaction->self)->executing_reaction = reaction;
      |                                                         ^
In file included from /home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor.h:62,
                 from /home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:49:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c: In function ‘initialize’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:1706:35: error: expected ‘)’ before ‘PRINTF_TIME’
 1706 |     LF_PRINT_DEBUG("Start time: " PRINTF_TIME "ns", start_time);
      |                                   ^~~~~~~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/utils/util.h:178:36: note: in definition of macro ‘LF_PRINT_DEBUG’
  178 |                     lf_print_debug(format, ##__VA_ARGS__); \
      |                                    ^~~~~~
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c: In function ‘termination’:
/home/byeonggil-jun/lingua-franca/test/C/src-gen/Hello/core/reactor_common.c:1744:70: error: expected ‘)’ before ‘PRINTF_TIME’
 1744 |         lf_print_warning("---- The first future event has timestamp " PRINTF_TIME " after start time.", event_time);
      |                                                                      ^~~~~~~~~~~~
      |                                                                      )
make[2]: *** [core/CMakeFiles/core.dir/build.make:118: core/CMakeFiles/core.dir/reactor_common.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:126: core/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Compiled binary is in /home/byeonggil-jun/lingua-franca/test/C/bin
lfc: error:  failed with error code 2
 --> (unknown file):null:1 -  failed with error code 2

lfc: fatal error: Aborting due to previous error
```
5. It is compiled well when I run `rm -rf test/C/src-gen` and then `./gradlew runLfc --args test/C/src/Hello.lf`.

Does this error occur only for me?

**Comment by cmnrd** [comment] 2023-02-20 16:22
I cannot reproduce this error. On which version are you? Did you try to pull a recent version from master?

**Comment by byeong-gil** [comment] 2023-02-23 04:29
Yes, I did. I'm using the most recent version. And I still suffer from this error. Did you modify `lf` file before recompiling?
This error only occurs when I try to recompile an `lf` file while I don't delete the previous compilation's `src-gen` folder.

**Comment by cmnrd** [comment] 2023-02-28 09:18
Yes, I used exactly the steps that you outlined, and it works just fine on my end.

On which OS are you working on?

**Comment by byeong-gil** [comment] 2023-03-03 00:41
I'm working on Linux (ubuntu 20.04) now.

**Comment by cmnrd** [comment] 2023-03-03 08:55
This is really mysterious. I just tried again on Ubuntu 20.04 and also there everything works fine. Could I ask you to repeat your steps from above and zip the entire `test/C/` directory after your first run and after the second run? Preferably, you can send me both archives on our [zulip](https://lf-lang.zulipchat.com). Then I can hopefully better understand what is going on.

**Comment by byeong-gil** [comment] 2023-03-06 04:21
Sorry for making you waste some time, @cmnrd. Now, everything works well. I'm not sure, but I think it was some of my packages' problems. Because I recently updated some packages using `Synaptic Package Manager`. Again, I apologize for bothering you.

**Comment by cmnrd** [comment] 2023-03-06 08:18
No worries. I am glad the issue is resolved :)

**Closed by cmnrd** 2023-03-06 08:18 UTC
Labels: bug
