### ISSUE TITLE
RTI mistakenly gives PTAG in ChainWithDelay

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2084] opened 2023-11-05 16:40 UTC
Here is the trace of the execution. The RTI gives a PTAG of 3msec to `t`, then later it receives a MSG with tag 2.5msc

![image](https://github.com/lf-lang/lingua-franca/assets/21197938/d9fbe4d5-d97b-4db2-8099-2644f1d7276e)

**Comment by erlingrj** [comment] 2023-11-05 16:49
Here is the full trace: https://drive.google.com/file/d/1hP45U4hTVSXHXVSR9mvozkT5yzyO5PDQ/view?usp=sharing

**Comment by byeong-gil** [comment] 2023-11-24 13:55
@edwardalee @hokeun I think this is the same problem as [`AfterDelays.lf`](https://github.com/lf-lang/lingua-franca/blob/master/test/C/src/federated/AfterDelays.lf). Also, I found one reason for this problem. I'm still debugging this, so I'm not sure this is the only reason. 

The problem I found is, that **A federate sends incorrect LTC messages when it executes a dummy event caused by a PTAG**. 

I'd explain more with a simple example. The sender just sends a message every 20 msec. And I changed the RTI to not forward tagged messages it receives (see this [commit](https://github.com/lf-lang/reactor-c/pull/312/commits/955b7a8f971c07bd6ab298ca025dcebf88bfa61d) in [reactor-c PR#312](https://github.com/lf-lang/reactor-c/pull/312)). 
![image](https://github.com/lf-lang/lingua-franca/assets/78055940/ced6fe42-d4a8-4ebf-ad22-b798039049ab)

This is the trace of the experiment. The RTI didn't forward T_MSG (1 msec). However, `federate_r` sent LTC (1 msec) without waiting for the network input at 1 msec. 
![image](https://github.com/lf-lang/lingua-franca/assets/78055940/861f8611-c554-4d3e-9033-828abc7e90a3)

Additionally, I found a weird point about the order of PTAG and T_MSG. I'll update you about it soon after I complete the debugging.

**Comment by edwardalee** [comment] 2023-11-24 14:28
Ah, this looks like a good lead! Nice detective work!I found a couple of problems with my implementation in enclaves3 and pushed fixes.However, I don’t think they were related to this, and I may have been too optimistic in also pushing a fix that disables PTAG except when there is a zero delay loop.  You should merge in my fixes, then change your example to have a zero delay loop.  If the problem persists, then my fixes indeed had nothing to do with this.Alternatively, it would be easy to reverse my change and reinstate the excessive use of PTAG.I’m also working on eliminating the absent messages except when there is a zero delay cycle.Edward---------Edward A. LeeEECS, UC ***@***.***://eecs.berkeley.edu/~ealOn Nov 24, 2023, at 5:55 AM, Byeonggil Jun ***@***.***> wrote:﻿
@edwardalee @hokeun I think this is the same problem as AfterDelays.lf. Also, I found one reason for this problem. I'm still debugging this, so I'm not sure this is the only reason.
The problem I found is, that A federate sends incorrect LTC messages when it executes a dummy event caused by a PTAG.
I'd explain more with a simple example. The sender just sends a message every 20 msec. And I changed the RTI to not forward tagged messages it receives (see this commit in reactor-c PR#312).

This is the trace of the experiment. The RTI didn't forward T_MSG (1 msec). However, federate_r sent LTC (1 msec) without waiting for the network input at 1 msec.

Additionally, I found a weird point about the order of PTAG and T_MSG. I'll update you about it soon after I complete the debugging.

**Comment by byeong-gil** [comment] 2023-11-25 01:35
Thank you, professor! I reversed the change you made in the branch `reactor-c/ptag-debug`, (please refer to [this PR](https://github.com/lf-lang/reactor-c/pull/312)).

**Comment by lhstrh** [comment] 2024-01-06 02:33
@edwardalee, are there changes in #2140 that are meant to fix this?

**Comment by byeong-gil** [comment] 2024-02-19 03:10
> @edwardalee, are there changes in #2140 that are meant to fix this?

https://github.com/lf-lang/lingua-franca/pull/2140 fixed this as it removed PTAG messages from `ChainWithDelay.lf` at all.

**Closed by byeong-gil** 2024-02-19 03:10 UTC
Labels: bug, c, federated
